"use client";

import { useEffect, useState, useCallback, useRef } from "react";
import Link from "next/link";
import { Lock, Trash2, Pencil, X, Check, Loader2, ShieldAlert, LogOut, ImagePlus, Sparkles, Wand2, FileText, CopyCheck, Search } from "lucide-react";
import { fetchBooks, verifyAdminPassword, adminUpdateBook, adminDeleteBook, adminUploadCover, adminGenerateCover, adminGenerateAllCovers, fetchDuplicateGroups, getStoredAdminPassword, storeAdminPassword, clearAdminPassword, formatSize, getCoverUrl, type Book, type GenerateAllCoversResult, type DuplicateGroup } from "@/lib/api";
import BulkImportPanel from "@/components/BulkImportPanel";

function CoverThumb({ book, password, onUpdated }: { book: Book; password: string; onUpdated: (b: Book) => void }) {
  const [failed, setFailed] = useState(false); const [uploading, setUploading] = useState(false); const [generating, setGenerating] = useState(false); const [error, setError] = useState(""); const fileInputRef = useRef<HTMLInputElement>(null);
  const hasCover = !!book.cover_message_id && !failed; const busy = uploading || generating;
  async function pick(e: React.ChangeEvent<HTMLInputElement>) { const file = e.target.files?.[0]; e.target.value = ""; if (!file) return; setUploading(true); try { const b = await adminUploadCover(book.id, password, file); setFailed(false); onUpdated(b); } catch { setError("Upload failed"); } finally { setUploading(false); } }
  async function generate() { setGenerating(true); setError(""); try { const b = await adminGenerateCover(book.id, password, true); setFailed(false); onUpdated(b); } catch { setError("Generate failed"); } finally { setGenerating(false); } }
  return <div className="shrink-0 flex flex-col items-center gap-1.5"><div className="relative w-14 h-[74px] rounded-lg overflow-hidden border border-slate-700 bg-slate-800 flex items-center justify-center">{hasCover ? <img src={getCoverUrl(book.id, book.updated_at)} alt="" className="w-full h-full object-cover" onError={() => setFailed(true)} /> : <FileText className="w-5 h-5 text-slate-600" />}{busy && <div className="absolute inset-0 bg-black/60 flex items-center justify-center"><Loader2 className="w-4 h-4 animate-spin text-white" /></div>}</div><div className="flex gap-1"><input ref={fileInputRef} type="file" accept="image/jpeg,image/png,image/webp" className="hidden" onChange={pick} /><button type="button" onClick={() => fileInputRef.current?.click()} disabled={busy} className="p-1 rounded text-slate-400 hover:text-brand-400 disabled:opacity-50" title="Upload cover"><ImagePlus className="w-3.5 h-3.5" /></button><button type="button" onClick={generate} disabled={busy} className="p-1 rounded text-slate-400 hover:text-brand-400 disabled:opacity-50" title="Generate cover"><Wand2 className="w-3.5 h-3.5" /></button></div>{error && <p className="text-[10px] text-rose-400">{error}</p>}</div>;
}

export default function AdminPage() {
  const [password, setPassword] = useState<string | null>(null); const [passwordInput, setPasswordInput] = useState(""); const [authError, setAuthError] = useState(""); const [checking, setChecking] = useState(false);
  const [books, setBooks] = useState<Book[]>([]); const [total, setTotal] = useState(0); const [loadingBooks, setLoadingBooks] = useState(false); const [loadBooksError, setLoadBooksError] = useState(""); const [query, setQuery] = useState("");
  const [editingId, setEditingId] = useState<string | null>(null); const [editForm, setEditForm] = useState<Partial<Book>>({}); const [actionError, setActionError] = useState(""); const [deletingId, setDeletingId] = useState<string | null>(null);
  const [generatingAll, setGeneratingAll] = useState(false); const [generateAllResult, setGenerateAllResult] = useState<GenerateAllCoversResult | null>(null); const [checkingDuplicates, setCheckingDuplicates] = useState(false); const [duplicateGroups, setDuplicateGroups] = useState<DuplicateGroup[] | null>(null); const [removingDupId, setRemovingDupId] = useState<string | null>(null);

  useEffect(() => { const stored = getStoredAdminPassword(); if (stored) setPassword(stored); }, []);
  const loadBooks = useCallback(async (search = "") => { if (!password) return; setLoadingBooks(true); setLoadBooksError(""); try { const res = await fetchBooks({ q: search.trim() || undefined, limit: 200, offset: 0 }); setBooks(res.books); setTotal(res.total); } catch (err) { setLoadBooksError(err instanceof Error ? err.message : "Failed to load books."); } finally { setLoadingBooks(false); } }, [password]);
  useEffect(() => { if (!password) return; const timer = window.setTimeout(() => loadBooks(query), 250); return () => window.clearTimeout(timer); }, [password, query, loadBooks]);

  function handleCoverUpdated(b: Book) { setBooks(prev => prev.map(x => x.id === b.id ? b : x)); }
  async function handleGenerateAll() { if (!password) return; setGeneratingAll(true); setGenerateAllResult(null); try { const r = await adminGenerateAllCovers(password); setGenerateAllResult(r); await loadBooks(query); } catch (e) { setActionError(e instanceof Error ? e.message : "Couldn't generate covers."); } finally { setGeneratingAll(false); } }
  async function handleFindDuplicates() { if (!password) return; setCheckingDuplicates(true); try { const r = await fetchDuplicateGroups(password); setDuplicateGroups(r.groups); } catch (e) { setActionError(e instanceof Error ? e.message : "Couldn't check for duplicates."); } finally { setCheckingDuplicates(false); } }
  async function handleRemoveDuplicate(id: string) { if (!password) return; setRemovingDupId(id); try { await adminDeleteBook(id, password); setBooks(prev => prev.filter(b => b.id !== id)); setDuplicateGroups(prev => prev?.map(g => ({...g, books:g.books.filter(b => b.id !== id)})).filter(g => g.books.length > 1) || null); } catch (e) { setActionError(e instanceof Error ? e.message : "Couldn't remove duplicate."); } finally { setRemovingDupId(null); } }
  async function handleLogin(e: React.FormEvent) { e.preventDefault(); setChecking(true); setAuthError(""); try { const ok = await verifyAdminPassword(passwordInput); if (!ok) { setAuthError("Incorrect password."); return; } storeAdminPassword(passwordInput); setPassword(passwordInput); } catch { setAuthError("Couldn't reach the server. Try again."); } finally { setChecking(false); } }
  function logout() { clearAdminPassword(); setPassword(null); setPasswordInput(""); }
  const handleSessionExpired = useCallback(() => { clearAdminPassword(); setPassword(null); setPasswordInput(""); setActionError("Your session expired — log in again."); }, []);
  function startEdit(b: Book) { setEditingId(b.id); setEditForm({title:b.title, author:b.author, description:b.description, language:b.language, tags:b.tags}); }
  async function saveEdit(id: string) { if (!password) return; try { const b = await adminUpdateBook(id, password, editForm); setBooks(prev => prev.map(x => x.id === id ? b : x)); setEditingId(null); } catch (e) { setActionError(e instanceof Error ? e.message : "Couldn't save changes."); } }
  async function handleDelete(id: string) { if (!password || !confirm("Remove this book from the library? The file stays in Telegram.")) return; setDeletingId(id); try { await adminDeleteBook(id, password); setBooks(prev => prev.filter(b => b.id !== id)); setTotal(t => Math.max(0,t-1)); } catch (e) { setActionError(e instanceof Error ? e.message : "Couldn't delete this book."); } finally { setDeletingId(null); } }

  if (!password) return <div className="max-w-sm mx-auto px-4 py-24"><div className="flex flex-col items-center text-center gap-3 mb-8"><div className="w-12 h-12 rounded-2xl bg-brand-500/15 flex items-center justify-center"><Lock className="w-5 h-5 text-brand-400" /></div><h1 className="text-xl font-bold text-slate-100">Admin access</h1><p className="text-sm text-slate-500">Enter the admin password to manage books.</p></div><form onSubmit={handleLogin} className="space-y-3"><input type="password" autoFocus value={passwordInput} onChange={e=>setPasswordInput(e.target.value)} placeholder="Password" className="w-full bg-slate-900 border border-slate-800 rounded-xl px-4 py-2.5 text-slate-100" />{authError&&<p className="text-sm text-rose-400"><ShieldAlert className="inline w-4 h-4 mr-1" />{authError}</p>}<button type="submit" disabled={checking||!passwordInput} className="w-full flex items-center justify-center gap-2 bg-brand-600 disabled:opacity-50 text-white font-medium py-2.5 rounded-xl">{checking&&<Loader2 className="w-4 h-4 animate-spin" />}Sign in</button></form></div>;

  return <div className="max-w-5xl mx-auto px-4 py-8"><div className="flex flex-wrap items-center justify-between mb-6 gap-4"><div><h1 className="text-xl font-bold text-slate-100">Manage books</h1><p className="text-sm text-slate-500">{total.toLocaleString()} books · showing {books.length}</p></div><div className="flex items-center gap-3"><Link href="/admin/recommendations" className="text-sm text-slate-400 hover:text-brand-300">Recommendations</Link><button onClick={handleFindDuplicates} disabled={checkingDuplicates} className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-slate-700 text-slate-300 text-sm disabled:opacity-50">{checkingDuplicates?<Loader2 className="w-3.5 h-3.5 animate-spin"/>:<CopyCheck className="w-3.5 h-3.5"/>}Find duplicates</button><button onClick={handleGenerateAll} disabled={generatingAll} className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-slate-700 text-slate-300 text-sm disabled:opacity-50">{generatingAll?<Loader2 className="w-3.5 h-3.5 animate-spin"/>:<Sparkles className="w-3.5 h-3.5"/>}Generate all covers</button><button onClick={logout} className="flex items-center gap-1.5 text-sm text-slate-400 hover:text-rose-400"><LogOut className="w-4 h-4"/>Sign out</button></div></div>
  <BulkImportPanel password={password} onImported={()=>loadBooks(query)} onSessionExpired={handleSessionExpired} />
  <div className="mt-5 relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-600"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search title or author — searches all 17,124 books" className="w-full bg-slate-900 border border-slate-800 rounded-xl pl-10 pr-4 py-3 text-sm text-slate-100 placeholder:text-slate-600"/></div>
  {generateAllResult&&<div className="my-4 text-sm text-slate-300 bg-slate-900/60 border border-slate-800 rounded-xl px-4 py-2.5">Generated {generateAllResult.generated} covers{generateAllResult.skipped>0&&` · skipped ${generateAllResult.skipped}`}{generateAllResult.failed.length>0&&` · ${generateAllResult.failed.length} failed`}.</div>}
  {duplicateGroups&&<div className="my-4 bg-slate-900/60 border border-slate-800 rounded-xl px-4 py-3 space-y-3">{duplicateGroups.length===0?<p className="text-sm text-slate-400"><CopyCheck className="inline w-4 h-4 mr-1"/>No duplicates found.</p>:duplicateGroups.map((g,i)=><div key={i} className="border border-slate-800 rounded-lg p-3 space-y-2"><p className="text-xs text-slate-500">{g.method === "identical_file" ? "Identical file content" : "Same filename & size"}</p>{g.books.map(b=><div key={b.id} className="flex items-center justify-between gap-3 text-sm"><span className="truncate text-slate-200">{b.suggested_keep&&"★ "}{b.title} <span className="text-slate-500">({formatSize(b.size)})</span></span><div className="flex gap-2"><Link href={`/book/${b.id}`} className="text-xs text-slate-400">View</Link><button onClick={()=>handleRemoveDuplicate(b.id)} disabled={removingDupId===b.id} className="text-xs px-2 py-1 rounded-lg border border-rose-900/60 text-rose-400">{removingDupId===b.id?"…":"Remove"}</button></div></div>)}</div>)}</div>}
  {loadBooksError&&<div className="my-4 text-sm text-rose-400 bg-rose-500/10 border border-rose-500/20 rounded-xl px-4 py-2.5"><ShieldAlert className="inline w-4 h-4 mr-1"/>{loadBooksError}</div>}
  {actionError&&<div className="my-4 text-sm text-rose-400 bg-rose-500/10 border border-rose-500/20 rounded-xl px-4 py-2.5">{actionError}</div>}
  {loadingBooks?<div className="flex items-center gap-2 text-slate-500 py-16 justify-center"><Loader2 className="w-5 h-5 animate-spin"/>Loading books…</div>:<div className="rounded-2xl border border-slate-800 overflow-hidden">{books.map(book=><div key={book.id} className="border-b border-slate-800 bg-slate-900/40">{editingId===book.id?<div className="p-4 space-y-3"><div className="grid sm:grid-cols-2 gap-3"><input value={editForm.title??""} onChange={e=>setEditForm(f=>({...f,title:e.target.value}))} placeholder="Title" className="bg-slate-800 border border-slate-700 rounded-lg px-3 py-2 text-sm text-slate-100"/><input value={editForm.author??""} onChange={e=>setEditForm(f=>({...f,author:e.target.value}))} placeholder="Author" className="bg-slate-800 border border-slate-700 rounded-lg px-3 py-2 text-sm text-slate-100"/></div><textarea value={editForm.description??""} onChange={e=>setEditForm(f=>({...f,description:e.target.value}))} placeholder="Description" rows={2} className="w-full bg-slate-800 border border-slate-700 rounded-lg px-3 py-2 text-sm text-slate-100"/><input value={(editForm.tags??[]).join(", ")} onChange={e=>setEditForm(f=>({...f,tags:e.target.value.split(",").map(t=>t.trim()).filter(Boolean)}))} placeholder="Tags, comma separated" className="w-full bg-slate-800 border border-slate-700 rounded-lg px-3 py-2 text-sm text-slate-100"/><div className="flex gap-2"><button onClick={()=>saveEdit(book.id)} className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-brand-600 text-white text-sm"><Check className="w-3.5 h-3.5"/>Save</button><button onClick={()=>setEditingId(null)} className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-slate-700 text-slate-300"><X className="w-3.5 h-3.5"/>Cancel</button></div></div>:<div className="p-4 flex items-center gap-4"><CoverThumb book={book} password={password} onUpdated={handleCoverUpdated}/><div className="min-w-0 flex-1"><Link href={`/book/${book.id}`} className="font-medium text-slate-100 hover:text-brand-300 truncate block">{book.title}</Link><p className="text-sm text-slate-500 truncate">{book.author||"Unknown author"} · {formatSize(book.size)} · reader: {book.reader_status||"unknown"}</p></div><div className="flex items-center gap-1 shrink-0"><button onClick={()=>startEdit(book)} className="p-2 rounded-lg text-slate-400 hover:text-brand-400" title="Edit"><Pencil className="w-4 h-4"/></button><button onClick={()=>handleDelete(book.id)} disabled={deletingId===book.id} className="p-2 rounded-lg text-slate-400 hover:text-rose-400 disabled:opacity-50" title="Delete">{deletingId===book.id?<Loader2 className="w-4 h-4 animate-spin"/>:<Trash2 className="w-4 h-4"/>}</button></div></div>}</div>)}</div>}
  </div>;
}
